### ISSUE TITLE
Tool not starting: Convert image format

### ISSUE THREAD

**Issue by ThomasWollmann** [bgruening/docker-galaxy-imaging#2]
```
Traceback (most recent call last):
  File "/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iuc/imagej2_convert_format/a3806b0a32ed/imagej2_convert_format/imagej2_convert_format.py", line 4, in <module>
    import imagej2_utils
  File "/export/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iuc/imagej2_convert_format/a3806b0a32ed/imagej2_convert_format/imagej2_utils.py", line 1, in <module>
    import bioformats
ImportError: No module named bioformats
```

**Comment by gregvonkuster** [comment]
@ThomasWollmann @bgruening I eliminated the imagej2_convert_format tool from the git repo when I de-multiplexed the ImageJ2 tools.  This tool is really not necessary and was the first tool I developed for the ImageJ2 suite, so I was not aware at that time that ImageJ2 has its own built-in conversion capability.  So for now, this tool can be eliminated from the docker image.  If we feel that we want to keep a version of this tool, it should be re-written to use only ImageJ2 with no dependency on bioformats.  I can do this if you want to keep this tool - please just open an issue and ping me.  I'll get it done as soon as I can, but it may take a bit of time.  ;)

**Comment by ThomasWollmann** [comment]
O.K. I'll remove it from the image.
